# Generated by Django 5.1.3 on 2024-12-06 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_foto_gato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField(auto_now_add=True)),
                ('gato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
