# Generated by Django 5.1.3 on 2024-12-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adocoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
